spring:
  main:
    banner-mode: "off"
  application:
    name: money-load-velocity-limit
  datasource:
    url: jdbc:h2:mem:moneyload;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
  flyway:
    enabled: true

velocity:
  limits:
    daily-amount: "5000.00"
    weekly-amount: "20000.00"
    daily-count: 3

management:
  endpoints:
    web:
      exposure:
        include: health
